# Generated by Django 2.2.3 on 2019-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'in progress'), ('2', 'done'), ('3', 'failed')], default='0', max_length=3)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
