# Generated by Django 2.2.3 on 2019-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_parser', '0002_auto_20190710_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
